version: '3'
services:
  web:
    build:
      context: .

    container_name: aps-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    links:
      - database
    depends_on:
      - database
  database:
    image: mysql:5.7
    container_name: aps-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aps_estagio
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  data:
